Update ta.po: add copyright, first author
bottlesdevs/Bottles pull request #1954
Opened 2022-08-17 16:48 UTC by kbdharun

**I am adding information about copyright and the first author to ta.po (Tamil translation file).** 

I have been using bottles for some time. It has been a fantastic and smooth experience running applications and games under bottles. I Thank you guys for creating and maintaining this project. Translating Bottles to Tamil is just a small contribution from me to this project. Planning to contribute more in the future. 

Regards,
Dharun

2022-08-17 19:40 UTC, mirkobrombin commented
Thanks for your contribution!

2022-08-17 20:36 UTC, TheEvilSkeleton requested changes
Just a minor change and it should be ready to merge.

2022-08-17 20:36 UTC, TheEvilSkeleton commented on po/ta.po
> +# Copyright (C) 2022 THE BOTTLE'S COPYRIGHT HOLDER
```suggestion
# Copyright (C) 2022 Bottles Contributors
```

2022-08-18 03:58 UTC, TheEvilSkeleton approved these changes

2022-08-18 03:59 UTC, merged