Addresses bug from patoolib
bottlesdevs/Bottles pull request #2498
Opened 2023-01-07 17:46 UTC by dkeruza-neo

# Description
Fixes a bug in "patoolib" that does not extract .tar.xz files correctly if you have xz or 7z installed in your system.
Also added a check to return False when a source DLL is being copied to the wine prefix and the source file does not exist. 
Fixes #(???)

## Type of change
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
To reproduce, install xz or 7z

2023-01-08 01:07 UTC, TheEvilSkeleton requested changes

2023-01-08 01:07 UTC, TheEvilSkeleton commented on bottles/backend/managers/dependency.py
> +                    logging.info(f"File/s not found in {path}")
```suggestion
                    logging.info(f"File(s) not found in {path}")
```

2023-01-08 20:34 UTC, TheEvilSkeleton commented
I rather not be the one to approve or reject it, as I don't have the time to test right now. I think someone else should review it.

2023-01-09 08:57 UTC, mirkobrombin approved these changes

2023-01-09 17:28 UTC, TheEvilSkeleton approved these changes

2023-01-09 17:29 UTC, merged