Don't enable Steam Runtime when switching to `wine-ge-proton`
bottlesdevs/Bottles pull request #2593
Opened 2023-01-20 20:53 UTC by SuperSamus

# Description
`wine-ge-proton` contains `proton` in its name, which caused Bottles to enable the Steam Runtime.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-01-21 12:47 UTC, Kinsteen submitted a review, later dismissed

2023-01-21 13:23 UTC, TheEvilSkeleton commented
If I remember right, this was actually intended, because it's made for Steam. @mirkobrombin thoughts?

2023-01-21 13:24 UTC, Kinsteen commented
@TheEvilSkeleton No, Proton-GE is intended for Steam. Wine-GE can and should be used without Steam. I don't know why "-proton" was added, but it definitely shouldn't force enable the Steam runtime

2023-01-21 13:32 UTC, TheEvilSkeleton commented
Wait, what is this one? I know of wine-ge-custom and proton-ge-custom. I've never heard of wine-ge-proton.

2023-01-21 13:34 UTC, Kinsteen commented
Because it doesn't exist, this is Wine-GE aka wine-ge-proton. For some reason, @koplo199 added "proton" to the name of Wine-GE here: https://github.com/bottlesdevs/components/pull/190

Why was this change needed?

2023-01-21 16:06 UTC, koplo199 commented
@Kinsteen Interesting, I originally changed it because:

1. It is the official name (see [titles](https://github.com/GloriousEggroll/wine-ge-custom/releases): it is `Wine-GE-Proton7-35 Released`, not `Wine-GE-7-35 Released`)
2. It is consistent with other components/runners names: they all fit the `{prefix}-{tag}` naming scheme, including `wine-ge`: `{wine}-{GE-Proton7-35}` (using again the official GitHub repository [tags](https://github.com/GloriousEggroll/wine-ge-custom/tags))
3. Any attempt to use the old name would have required a special handling/tweak/hack just to support it, and the more hack there is, the more difficult it becomes to maintain.

To me, the bug here is on the core side and not on the component side: whether the runner is a proton/wine one shouldn't be guessed by checking a list of hard-coded names when the components [yml files](https://github.com/bottlesdevs/components/blob/main/input_files/10-GE-Proton.yml#L2-L3) already specify `Sub-category: proton` or `Sub-category: wine`.

I see that in [manager.py](https://github.com/bottlesdevs/Bottles/blob/main/bottles/backend/managers/manager.py) there is:
https://github.com/bottlesdevs/Bottles/blob/0bb66aa328e7914a90c248826797d077dd56af90/bottles/backend/managers/manager.py#L100-L101
Could we instead of hard-coding the name, just check if the runner is contained in `supported_proton_runners`? Would it be an acceptable fix?

2023-01-21 16:14 UTC, Kinsteen commented on bottles/backend/runner.py
> +        if "proton" in runner.lower() and not runner.startswith("wine-ge-proton") and RuntimeManager.get_runtimes("steam"):
```suggestion
        if runner in manager.supported_proton_runners and RuntimeManager.get_runtimes("steam"):
```

2023-01-21 16:15 UTC, Kinsteen commented
@koplo199 It would be a perfect fix, even more so than what we had before. I tested quickly, and it seemed to work fine. More tests would be welcome, but I think it's the way to go.

2023-01-21 18:04 UTC, SuperSamus commented
Looking around the code, it seems that `"Proton" in runner` is used in multiple places, like [here](https://github.com/bottlesdevs/Bottles/blob/6954b8ad74f6ea68a5545fbe7d169f9f447760fb/bottles/backend/wine/winecommand.py#L419), or [here](https://github.com/bottlesdevs/Bottles/blob/6954b8ad74f6ea68a5545fbe7d169f9f447760fb/bottles/backend/wine/winecommand.py#L512). (Just grep `"proton"`/`"Proton"` to find them)
I guess these should be changed too, but I'm not familiar with the codebase (nor with Python), so I don't know how I should do `manager.supported_proton_runners` in these cases.

2023-01-21 18:08 UTC, Kinsteen commented
Okay. Would you be more comfortable closing this, and letting someone else do it, and change this like I suggested so we could merge? Someone else can do the other occurrences of this behavior, if you don't want to do it.

2023-02-12 17:03 UTC, Kinsteen requested changes

2023-02-12 17:03 UTC, Kinsteen commented on bottles/backend/managers/manager.py
> +            if runner in self.supported_proton_runners:
```suggestion
            if runner not in self.supported_proton_runners:
```
If I'm not mistaken, we add this lock only if it's *not* a Proton runner

2023-02-20 08:52 UTC, merged