frontend: Fix applying style classes
bottlesdevs/Bottles pull request #2809
Opened 2023-03-21 10:04 UTC by jannuary

# Description
Removes the silly code adding styles and bundles them in CSS instead, has a sideeffect of not causing a crash on GTK 4.10
Fixes #2788

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [ ] Test A
- [ ] Test B

2023-03-22 00:13 UTC, TheEvilSkeleton requested changes

2023-03-22 00:13 UTC, TheEvilSkeleton commented on bottles/frontend/ui/dialog-installer.blp
> +            ]
```suggestion
              styles [
                "installer",
              ]
```

2023-03-23 16:50 UTC, TheEvilSkeleton commented
Works on my end

2023-03-23 16:50 UTC, merged

2023-04-25 18:20 UTC, Mic92 commented
Can we get a release for this?